runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: bootstrap

- url: /templates
  static_dir: templates
  application_readable: true

- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: /search.*
  script: python.frontend.search.app

- url: /about
  script: python.frontend.about.app

- url: /albums.*
  script: python.frontend.albumpage.app

- url: /bands.*
  script: python.frontend.bandpage.app

- url: /tracks.*
  script: python.frontend.trackpage.app

- url: /profiles.*
  script: python.frontend.profilepage.app

- url: /toplists.*
  script: python.frontend.toplistpage.app

#API START
- url: /api/albums.*
  script: python.api.album.app

- url: /api/bands.*
  script: python.api.band.app

- url: /api/tracks.*
  script: python.api.track.app

- url: /api/accounts.*
  script: python.api.account.app

- url: /api/toplists.*
  script: python.api.toplist.app
#API END
# [END handlers]
- url: /.*
  script: python.frontend.main.app
# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
